# Using version 2.6 of the compose format
version: '3.6'

# Services Section
services:
  # Sakai Service
  sakai:
    # LOCAL image, fine for a single machine, but for a cluster
    # you should use a repo (e.g. mydockerhubrepo/sakai:19.1)      
    image: sakai
    # Forward port 8080 on the docker host (left) to port 8080
    # inside the service (right)
    ports:
      - "8080:8080"
    # Explicitly set any environment variables, in this case Tomcat memory
    environment:
      - "CATALINA_OPTS_MEMORY=-Xms4000m -Xmx4000m"
    # Map Docker managed configs into the service
    configs:
      # Mapping the sakai configuration to a different location 
      # instead of /usr/local/sakai/properties/sakai.properties
      # So our overridden entrypoint script can make changes
      # before placing the finished file
      - source: sakai_config
        target: /usr/local/sakai/es.properties
      # Providing an entrypoint script to override the default with.
      # This script will finish calling the original entrypoint.
      - source: elastic_entry
        target: /es_entry.sh
    # A configuration file needs to be updated at runtime, with the interface name
    # of the "elastic" netowrk. This provides an example of how to get that done.
    # We override the entrypoint script of an image, with one that discovers the 
    # interface name using the known network range defined near the bottom, in the
    # networks section. This script is located at config/es_entry.sh and 
    # is mapped in the Configs section near the bottom.
    entrypoint: bash /es_entry.sh
    # The overlay networks to connect this service to. These are defined in the Networks 
    # section near the bottom of this file
    networks:
      - elastic
      - mysql
      - mail
    # The secrets to provide to this service. These are defined in the Secrets section
    # near the bottom of this file.
    secrets:
      - security.properties

  # MySQL service.      
  mysql:
    # Docker official image for MySQL 5.5
    image: mysql:5.5
    # Extra startup parameters for MySQL
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    # Environment Variables
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: sakai
      MYSQL_USER: sakai
      MYSQL_PASSWORD: examplepassword
    # Networks from section near bottom 
    networks:
      - mysql

  # Elasticsearch Service     
  elasticsearch:
    # Docker official Elasticsearch 1.7.6 image      
    image: elasticsearch:1.7.6
    # Environment variables
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # Configs from section near bottom
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    # Networks from section near bottom
    networks:
      - elastic
    # Using DNS Round Robin, to make the overlay netowrk the primary
    deploy:
      endpoint_mode: dnsrr

  # Cerebro service    
  cerebro:
    # 3rd party repo for Cerebro (Elasticsearch management)      
    image: lmenezes/cerebro
    # forward docker host 8082 to 9000 inside the service
    ports:
      - "8082:9000"
    # Networks from section near bottom
    networks:
      - elastic

  # Mailcatcher service      
  mailcatcher:
    # 3rd party repo fro Mailcatcher (Fake mail server for development and testing)
    image: schickling/mailcatcher
    # Forward docker host port 8081 to 1080 inside the service
    ports:
      - "8081:1080"
    # Networks from section near bottom
    networks:
      - mail

  kibana:
    image: kibana:4.1.11
    networks:
      - elastic
    ports:
      - "8083:5601"
    environment:
      - "SERVER_NAME=127.0.0.1"
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    environment:
      - "PMA_ARBITRARY=1"
    ports:
      - "8084:80"
    networks:
      - mysql
    
# Configuration files we want Docker to manage
configs:
  # The Sakai config using Mailcatcher as the outgoing SMTP
  # and Elasticsearch configuration with a placeholder value
  # to be replaced by the entrypoint script at runtime
  sakai_config:
    file: ./config/sakai.es.properties
  # The Elasticsearch config for elasticsearch service
  elastic_config:
    file: ./config/elasticsearch.yml
  # The entrypoint script being used to override the defaut in the sakai service
  elastic_entry:
    file: ./config/es_entry.sh

# Secrets files we want docker to manage
secrets:
  # Example security properties for the sakai servicer
  security.properties:
    file: ./secrets/security.properties

# Networks to be created, connected to services above
networks:
  # The elasticsearch overlay network, with a manually defined subnet
  # so that the entrypoint script in the sakai service can easily
  # identify the correct interface when configuring sakai search
  elastic:
    driver: overlay
    ipam:
      config:
        - subnet: 10.99.99.0/24
  # MySQL overlay netowrk
  mysql:
    driver: overlay
  # Mail overlay netowrk
  mail:
    driver: overlay
